### ISSUE TITLE
inrupt.com inserted into new landing pages

### ISSUE THREAD

**Issue by melvincarvalho** [nodeSolidServer/node-solid-server#1152]
Looking at the new release, it would appear that the inrupt.com domain has been inserted into new landing pages

Just wanted to question whether this was intentional or a slip.

https://github.com/solid/node-solid-server/blame/6afe43958c90abdab68324c1d3e5af35a16247ca/default-templates/server/index.html#L48

**Comment by megoth** [comment]
It was intentionally added, and in my mind at the time I thought https://solid.inrupt.com/docs to be the best resource for the documentation I was thinking about (and in many regards I still think that resource is the best resource). But I could've surveyed more, and asked the community more about which resource should be there.

Do you have a suggestion for a resource that is better to point to in this case?

@michielbdejong suggested maybe https://github.com/solid/userguide could be a better resource? But I think it should be updated a bit if we want to point to it, maybe have it as part of https://github.com/solid/node-solid-server/issues/1145 ?

**Comment by melvincarvalho** [comment]
Thanks for clarifying.  Question is answered.

**Comment by melvincarvalho** [comment]
I've tried quite hard to look at this from the perspective of a judgement call.  I'm just not able to get there, at least not right now.  So I'll "gently" add a thumbs down here.  It just seems to me as wrong to come to someone else's project and insert your url on the landing page in your first release.  Having registered my thoughts, and appreciating views on this may be varied, I will leave it at that.

**Comment by megoth** [comment]
@melvincarvalho well, in this case I don't feel that this is someone else's project, but _our_ project (as in us, the Solid FOSS community). I'm contributing to this project on the behalf of inrupt, and all of those contributions are done for the betterment of the Solid project.

If you disagree that notion, I think we should start another discussion (perhaps in another thread). But do note that I'm unsure what good would come out of it. There certainly are those skeptical about inrupt, and some probably wants us to fail in our endeavours, so it could become a flame war that doesn't really help the project.

All of inrupts' contributions to the open source projects are open to scrutiny, so please do interject when you find stuff that you're skeptical to, but please don't paint us at inrupt in an unfair light in the doing.

**Comment by melvincarvalho** [comment]
@megoth thanks for your response.  You are perhaps reading too much into my comment.  I appreciate your sincerity, and your good intentions.  Soild has come about through the contributions of many actors : academic, corporate and individuals, over a period of many years years.  Both you and inrupt to big part of that.  I think we are in general agreeing, it is in it a team effort!

**Comment by melvincarvalho** [comment]
@megoth also, I actually just had a look at the inrupt page.

I noticed the following : 

```JavaScript
<script>(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create", "UA-126652300-1", {"cookieDomain":"auto"});ga("set", "anonymizeIp", true);ga("send", "pageview");</script>
```

If I'm not mistaken (and I might be!) this is tracking software that uses google analytics.  

What that means is that someone installing node solid server would click on the "docs" link and would then be tracked by google, when they were expecting just to read some documentation.

I run solid to protect my privacy, but through clicking a seemingly innocent link, i inadvertently got tracked by google and inrupt.  I would personally consider this harmful.

**Comment by gobengo** [comment]
I share in the discomfort. Inrupt could just as easily contibute to the MIT-licensed https://github.com/solid/information

Strategically, I'd be surprised that management/board would allow any moves this early in the co that would undercut the OSS-community trust.

Another consideration other than analytics tracking is license. The code is MIT-licensed, as are the aforementioned docs at solid/information. @megoth, under what license are the inrupt.com docs published? I see `© 2019 Solid, All Rights Reserved.` in the bottom left corner of the website. What is "Solid" in this context? Is it a legal entity in the US?

**Comment by justinwb** [comment]
@melvincarvalho Regarding GA - see [this comment](https://github.com/solid/node-solid-server/issues/1153#issuecomment-476043575). Will track down what's calling it and get it stripped right away as it's not in use (Matomo is used instead). Thank you for raising!

**Comment by melvincarvalho** [comment]
@justinwb thanks alot for looking at this.  I think that's a plus.

It's still slightly problematic.

1. Firstly the @megoth [comment](https://github.com/solid/node-solid-server/issues/1152#issuecomment-475899642) I felt was unconstructive.  Nobody I know wants inrupt to fail, and everyone I know (including me) wants inrupt to succeed.  Otherwise I would not have donated hours of my time helping inrupt, and indeed writing some of the copy on the website.  On a long enough time line all companies die.  Some are faster, some are slower.  Comments such as the above are liable to turn inrupt into the Usain Bolt of dying.  Avoid.

2. The problem as I see it is that people went to inrupt dot com will be often those that care alot about privacy and surveillance.  And now, depending on how long this has happened, google and their partners probably have a list of people that are that way inclined.  You can make a good argument that google has this already, but our project was supposed be trying to push back against that model, at least a little bit.

3. It's not our call whether or not a company supporting solid uses google analytics, or even open source analytics.  That's really for the company in question.  There will be trade offs for such a decisions, and its more about messaging and communications than something technical.  We can however choose to which sites we link to, and they should be neutral, or have a degree of separation, for example github is generally accepted in FLOSS projects.

4. Whether or not to use GA is a corporate decision -- I mean other firms that support solid such as openlink do occasionally use it, and Im still a big fan of openlink.  What is concerning is that it seems to be official inrupt policy NOT to use GA, and it happened anyway.  And if it was (maybe?) you that put it there, AIUA you are not actually an inrupt employee.  That's a bit scary.  There is a slippery slope argument to be made there.  ie could it happen on inrupt.net, or could it happen on the solid project forum.  I think probably not, but what stops it.

5. Even using open source analytics will give you the referrer as noted in the inrupt [ToS](https://solid.inrupt.com/node/33) so that will generate a list of all the pods that click on the documentation link.  That might not be in line with what the pod owner was intending.  Subjectively, I dont at this point in time consider open source analytics harmful, but I've not thought alot about it.

Didnt really want to dwell on this issue, as I thought it to be closed, but there are still some slight niggles.  I'd suggest we just remove the documentation link from the template, as a temporary measure, until a better solution presents this itself.  It's just a text link in master and I think could be done by one of us as an emergency fix in a few seconds, if there's no objections.

**Comment by Mitzi-Laszlo** [comment]
Perhaps https://www.w3.org/community/solid/wiki/Main_Page is a good overview landing page?

**Comment by megoth** [comment]
> 1. Firstly the @megoth [comment](https://github.com/solid/node-solid-server/issues/1152#issuecomment-475899642) I felt was unconstructive.  Nobody I know wants inrupt to fail, and everyone I know (including me) wants inrupt to succeed.  Otherwise I would not have donated hours of my time helping inrupt, and indeed writing some of the copy on the website.  On a long enough time line all companies die.  Some are faster, some are slower.  Comments such as the above are liable to turn inrupt into the Usain Bolt of dying.  Avoid.

It was indeed not a constructive comment, and I'm sorry for that. I appreciate your contributions and past efforts, and did not intend to undermine that.

It is indeed a team effort, and I suggest that we change the URL of the documentation link to something more neutral. Maybe https://www.w3.org/community/solid/wiki/Main_Page is a good resource, as @Mitzi-Laszlo suggested? It links to other documentations as well, and the control of the page is more open for the community.

Can we agree to a resource that the documentation-link should point to, or should we remove it altogether?

**Comment by melvincarvalho** [comment]
@megoth thanks for your kind words, of course, apology accepted.

The w3c wiki page seems like an uncontroversial option.  I dont have a strong opinion on this.  Possibly in the longer term a documentation template or app would be good, and help those that dont have a net connection.

**Comment by Ryuno-Ki** [comment]
Regarding web analytics... I just opened https://github.com/solid/information/issues/76 - maybe we can continue there?

Is this issue resolved now?
I mean, inrupt.com was removed from the landing pages, wasn't it?

**Comment by gobengo** [comment]
Seems like there has been a flurry of activity from inrupt (at least @michielbdejong @Mitzi-Laszlo @megoth). But no answer to the licensing question.

In particular, the solid wiki's main page documentation section still just points to inrupt.com as the first link. What is the license of the documentation there, and who/what has the copyright?

Specifically, can I copy all the documentation from inrupt.com to the wiki?

**Comment by melvincarvalho** [comment]
> Platforms and products must be designed with privacy, diversity and security in mind.

Im inspired by tim's [open letter](https://webfoundation.org/2019/03/web-birthday-30/).  At this point I am rather confused about things.

> Is this issue resolved now?

Unanswered questions remain, but the original question as is relates to node solid server I think is resolved.  

@gobengo question on licensing is outstanding.  I am curious on this one too, since I was asked to author some of the content.

**Comment by melvincarvalho** [comment]
You might want to nix this too

```JavaScript
<!-- Go to www.addthis.com/dashboard to customize your tools --> 
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-52619d547665b7b3">
</script>
```

Tho I'm not sure entirely what it is.

**Comment by Mitzi-Laszlo** [comment]
> I share in the discomfort. Inrupt could just as easily contibute to the MIT-licensed https://github.com/solid/information
> 
> Strategically, I'd be surprised that management/board would support any moves this early in the co that would risk the OSS-community trust.
> 
> Another consideration other than analytics tracking is license. The code is MIT-licensed, as are the aforementioned docs at solid/information. @megoth, under what license are the inrupt.com docs published? I see `© 2019 Solid, All Rights Reserved.` in the bottom left corner of the website. What is "Solid" in this context? Is it a legal entity in the US?

Yes, can see how this is confusing. I have brought it up with the inrupt team who are looking into sorting it out.

**Comment by melvincarvalho** [comment]
> are looking into sorting it out

From my POV this cannot be "sorted out".  

I came to solid in order to build web sites that I would want to use myself as a user.  Ones that would not spy users.  One that would allow you to keep the reputation you have in one place and remix it in another.

Now the copy that I created to promote solid has been used to spy on users.  Something I promised myself I would never do, and the reason I started on this journey.

Disappointed.  But I will hold my nose and carry on.

**Comment by melvincarvalho** [comment]
@gobengo I merged your PR, as possibly a stop gap noting that the copy on the template could indeed be further amended.

Given the automagic of github it closed this issue, so I opened it again.

What started as a question ended up stumbling upon some other issues.  I think the main one, which remains outstanding, that inrupt might want to look at is the inclusion of addthis.  But that's really something internal for inrupt.

In retrospect my registered outrage may have been a slight over reaction.  As I observed today the uk parliament tv website also used google analytics, so I had a moan at them too, and asked them if they'd consider using matomo as well.  

I mean if it's good enough for Her Majesty, it ought to be good enough for one of her highest ranked commanders!

I do think the inquiry has lead to at least a partially positive outcome of removing an unwanted script.  So, happy to close if @gobengo is, noting there's some questions unrelated to the original that have been generated, which I am sure could be pursued further, if desired.

**Comment by gobengo** [comment]
@melvincarvalho Glad it was merged. I think it clearly resolves the original point of this issue.

> The code is MIT-licensed, as are the aforementioned docs at solid/information. @megoth, under what license are the inrupt.com docs published? I see © 2019 Solid, All Rights Reserved. in the bottom left corner of the website. What is "Solid" in this context? Is it a legal entity in the US?

I am still curious about these questions, and hope @Mitzi-Laszlo (with help of their colleagues) will share answers soon.

Since that outstanding quandry is only tangentially related to this Issue, I will not be offended if you close this issue. We can make another one for "What dies © Solid mean?" or, specifically, "What is the license of docs at https://solid.inrupt.com/docs?"

**Comment by csarven** [comment]
This issue was resolved by https://github.com/nodeSolidServer/node-solid-server/pull/1154
