### ISSUE TITLE
Cannot login on https://team.inrupt.net/

### ISSUE THREAD

**Issue by RubenVerborgh** [nodeSolidServer/node-solid-server#1244]
I cannot login to https://team.inrupt.net/ as https://ruben.verborgh.org/profile/#me.

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/675313/60296350-e94b1e80-98f3-11e9-89d7-7556773a803d.png">

This is likely a problem with `oidcIssuer` since I have the (more rare but valid) situation that my WebID https://ruben.verborgh.org/profile/#me is on a different host than my IDP https://drive.verborgh.org/.

**Comment by jaxoncreed** [comment]
Right, usually this should make a request out to your issuer, but maybe that's not happening.

**Comment by RubenVerborgh** [comment]
@jaxoncreed Would it be possible to have a look at this? I currently cannot access Inrupt documents, which is kind-of problematic 🙂

**Comment by csarven** [comment]
Can't reproduce.
