### ISSUE TITLE
Update to latest rdflib.js

### ISSUE THREAD

**Issue by michielbdejong** [nodeSolidServer/node-solid-server#1416]
A lot of work has been done on rdflib.js since version 0.21.
But there were breaking changes, and the NSS code would have to adapt to them.
For instance: https://github.com/linkeddata/rdflib.js/pull/401#issuecomment-608270542

**Comment by melvincarvalho** [comment]
Good idea in principle.  It looks like a significant change of over 500 commits.

Can we try to categorize which tests fail, and for what reason?
