### ISSUE TITLE
Proposal: work in the open, transparently

### ISSUE THREAD

**Issue by melvincarvalho** [nodeSolidServer/node-solid-server#1744]
When going to the people page, only 1 of the project members with merge access is visible

https://github.com/orgs/nodeSolidServer/people

![image](https://github.com/nodeSolidServer/node-solid-server/assets/65864/28d92317-6635-4257-9ab1-4491f1d57fd4)

Yet there are many more in the list working in private.  Who are they?:

Proposal:

1. anyone with merge access to nodesolidserver should work in the open, transparently
2. anyone who is not working in the open should be removed
3. if removed member wants to rejoin the project, they may, but must set their status to public
4. be open to new contributors, explain how to participate

Open source software, as the name implies, thrives on transparency, and dies with a lack of transparency.

Lets get node solid server back on the path of transparency.

**Comment by bourgeoa** [comment]
done
