### ISSUE TITLE
n3-patch

### ISSUE THREAD

**Issue by bourgeoa** [nodeSolidServer/node-solid-server#1747]
rdflib@2.3.33 implement n3-patch, migrate the NSS to use directly n3-patch.
Actually NSS uses a n3-patch parser to SPARQL
https://github.com/nodeSolidServer/node-solid-server/blob/main/lib/handlers/patch/n3-patch-parser.js

**Comment by zg009** [comment]
Alain are you referring to using this function for n3-patches?
https://github.com/linkeddata/rdflib.js/blob/7a40abfffcdfe7c31f8ada7b85677787641348c8/src/update-manager.ts#L860

**Comment by bourgeoa** [comment]
Well Rdflib has a way to construct a n3Patch https://github.com/linkeddata/rdflib.js/blob/7a40abfffcdfe7c31f8ada7b85677787641348c8/src/update-manager.ts#L815

NSS deliver n3Patch

And I don't know if he can consume them directly. Not sure

**Comment by zg009** [comment]
I think if the n3 patch parser is not being used to process N3 PATCH requests, another parser can be made that makes use of rdflib, and then processes N3 PATCH requests

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bourgeoa** [comment]
Yes but we have already one in NSS
Then the issue can be closed

**Comment by zg009** [comment]
I wrote some tests in n3-patch branch, if you could check.

I think there needs to be a request handler or middleware, to check if a PATCH request targets RDF content-type and body can be handled by n3 patch parser parsePatchDocument function. Then an integration test and it should work

**Comment by bourgeoa** [comment]
> Does this mean n3-patch is already working as intended, or is this an update to an old spec?

n3Patch is working as intended see patch 
- handler lib/handlers/patch.js
- and parsers lib/handlers/patch

**Comment by zg009** [comment]
OK then this issue can be closed?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
