### ISSUE TITLE
Unable to execute the bin/solid-init start command.

### ISSUE THREAD

**Issue by argahsuknesib** [nodeSolidServer/node-solid-server#1757]
Hello,
I wish to use the NSS for development, and want to use the bin/solid-test init for using the server without HTTPS and just HTTP.
I use the `bin/solid-test init` and subsequent `bin/solid-test start` but I still get an HTTPS connection.

Moreover, on requesting https://localhost:8443/ I get,
```
Can't find file requested: [object Object]
```

Thanks for your help!

**Comment by bourgeoa** [comment]
@argahsuknesib 
Personally I never use `init` but my own config file.
```
./bin/solid-test start --config-file myConfigFile.json
```
Can you paste the `config.file` created by `init`

**Comment by argahsuknesib** [comment]
Hello @bourgeoa , thanks for the reply.
The config file generated is, 
```
{
  "root": "/home/kush/Code/NSS/node-solid-server/data",
  "port": "8443",
  "serverUri": "https://localhost:8443",
  "webid": false,
  "mount": "/",
  "configPath": "./config",
  "configFile": "./config.json",
  "dbPath": "./.db",
  "sslKey": "/home/kush/Code/NSS/privkey.pem",
  "sslCert": "/home/kush/Code/NSS/fullchain.pem",
  "multiuser": false,
  "server": {
    "name": "localhost",
    "description": "",
    "logo": ""
  }
}
```
> I don't think NSS can run just as HTTP
So, the clients who write to the pod need to be authenticated or just make sure that the communication is encrypted?
I expect the authentication to work as the client requiring a write token to the pod.

**Comment by argahsuknesib** [comment]
Hello, works now!
I was expecting the root in the config
```
"root": "/home/kush/Code/NSS/node-solid-server/data",
```
to automatically create a ./data/ folder which it didn't. Thus, I manually created it and it works now.
