### ISSUE TITLE
username leak. remove "user found" from login page

### ISSUE THREAD

**Issue by emmettownsend** [nodeSolidServer/node-solid-server#1758]
anyone can scrape usernames from an NSS service by using the login page, since it discloses “user found”. ([CWE - CWE-200: Exposure of Sensitive Information to an Unauthorized Actor (4.13)](https://cwe.mitre.org/data/definitions/200.html) )
![Screenshot from 2024-02-20 14-03-27](https://github.com/nodeSolidServer/node-solid-server/assets/58346537/f45ae133-6053-4329-b958-aca8f15122a9)

**Comment by emmettownsend** [comment]
Davi found this defect yesterday. 
Looks like it could be fixed by just changing the error message sent back to the browser to something like...'The username and password combination is not valid'

**Comment by bourgeoa** [comment]
Thanks for reporting.
