### ISSUE TITLE
Username leakage from password reset mechanism

### ISSUE THREAD

**Issue by edwardsph** [nodeSolidServer/node-solid-server#1770]
In Reset Password `/account/password/reset`, if you enter a valid username you get 
![image-20240312-170029](https://github.com/nodeSolidServer/node-solid-server/assets/9445771/e5a088cd-f17b-4142-81bf-9f644f657319)
An invalid username results in
![image-20240312-170052](https://github.com/nodeSolidServer/node-solid-server/assets/9445771/b0d030a3-0120-4c10-93d7-93e7d0ed9537)
This can be used to confirm whether or not a username exists. It would be better if both cases resulted in the same message. That could be the original message or perhaps "A Reset Password link has been sent to the email associated with this username"

This is a simple fix but as it is a security issue, please could you do an immediate release.

See also: https://github.com/nodeSolidServer/node-solid-server/issues/1758

**Comment by bourgeoa** [comment]
It seems strange to have a `red error message` saying that there was `success`.

What do you think of sending : `Failed to send a Reset Password email` ?
Which is more generic.

**Comment by edwardsph** [comment]
The best practice recommendation is that the response is the same either way as in https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html

**Comment by zg009** [comment]
Hello Alain,

If the change needs to be made I already found the code which would be edited to fix.

https://github.com/nodeSolidServer/node-solid-server/blob/d8290cbe3f7fe5ba7ccd46e988a1591659c6de93/lib/requests/password-reset-email-request.js#L92-L98

Simply applying renderSuccess() on the final then and catch would suffice, though it may warrant renaming the method.

**Comment by bourgeoa** [comment]
I would do it here, this will maintain  all the logic, and add a comment line, why there is no throw Error

https://github.com/nodeSolidServer/node-solid-server/blob/d8290cbe3f7fe5ba7ccd46e988a1591659c6de93/lib/requests/password-reset-email-request.js#L126

Please do a PR
