### ISSUE TITLE
bin/solid-test does not exist

### ISSUE THREAD

**Issue by ricklyman** [nodeSolidServer/node-solid-server#816]
<html>
<pre>bash: /bin/solid-test: No such file or directory
</pre>
</html>

re: For testing purposes, you can use bin/solid-test with a self-signed certificate, generated as follows:

$ openssl genrsa 2048 > ../localhost.key
$ openssl req -new -x509 -nodes -sha256 -days 3650 -key ../localhost.key -subj '/CN=*.localhost' > ../localhost.cert

**Comment by melvincarvalho** [comment]
it should be there?

https://github.com/solid/node-solid-server/blob/master/bin/solid-test

does bin exist?

**Comment by melvincarvalho** [comment]
ah no leading / ... try ./bin/solid-test or bin/solid-test

**Comment by ricklyman** [comment]
I created a directory. I changed to the directory. I ran solid init. It
created a config  and data. I found solid-test in
/usr/local/lib/node_modules/solid-server/bin. When I run it, it does not
find the SSL key.

**Comment by kjetilk** [comment]
Could you check that the paths in `config.json` are correct?

**Comment by ricklyman** [comment]
config.json:
  "sslKey": "../",
  "sslCert": "../",
  
$ solid start
ERROR Can't find SSL key in ../

$ openssl genrsa 2048 > ../localhost.key
Generating RSA private key, 2048 bit long modulus
....................................................+++
...........................................+++
e is 65537 (0x010001)

$ openssl req -new -x509 -nodes -sha256 -days 3650 -key ../localhost.key -subj '/CN=*.localhost' > ../localhost.cert

$ solid start
ERROR Can't find SSL key in ../

$ /usr/local/lib/node_modules/solid-server/bin/solid-test start
ERROR Can't find SSL key in ../

**Comment by kjetilk** [comment]
Right, so these need to point to the actual files, so it looks like something went wrong in `solid init`. What do you think,  @dmitrizagidulin ?  

Anyway, we have #887 in the pipeline to be released soon. That may make this somewhat more intuitive too.

**Comment by melvincarvalho** [comment]
#887 is merged and there should be no issues here.

Suggest closing.

**Comment by kjetilk** [comment]
:+1:
