### ISSUE TITLE
Trying to create an empty container with Slug .scad

### ISSUE THREAD

**Issue by rimmartin** [nodeSolidServer/node-solid-server#894]
Hi,

cloned this project in the last hour and stood it up serving bin/solid-test for a local developer pod.
added a folder under public called scad. Then with the following code tried to make an empty container with Slug: '.scad'.  No errors but when I look with browser at https://roger.localhost:8443/public/scad/ I see an empty container '7fed9310',  

```
        solid.auth.fetch('https://roger.localhost:8443/public/scad/', {
           method: 'POST', 
           headers:{
            'Content-Type': 'text/turtle',
	    'Link': '<http://www.w3.org/ns/ldp#BasicContainer>; rel="type"',
            'Slug':  '.scad'
	   }
           }).then((res) => {return res;})
        .then((response) => {callback(null);})
        .catch(error => callback('Error: '+JSON.stringify(error)));

```

when I curl for '7fed9310'
```
 curl -k --cert ../roger-g74s.cert --key ../roger-g74s.key -G https://roger.localhost:8443/public/scad/7fed9310
Can't find file requested: data/roger.localhost/public/scad/7fed9310
```

it's not there.  Nor '.scad' either can be found.

**Comment by justinwb** [comment]
@rimmartin Thanks for the report. For us to determine the best way to respond to this, can you let me know if the following is an accurate summary of what you're reporting?

- You're looking to use the Slug header to inform the URI of the created container resource
- A resource is created, but not at the URI (.scad) that you specified in the Slug header
- when you try to access that created resource via curl, you can't find it

**Comment by rimmartin** [comment]
@justinwb , yes

have https://roger.localhost:8443/public/scad/
check and it exists and is pristine, no other operation or child has been attempted.  Then with the Slug I try to put an empty '.scad' container in it.  

The results wasn't the same any try where I blew away everything and came back with the server, user and run api again.
I made more attempts and put logs in the server code;  it looks like I'm hitting an internal pod meta folder name; there looks like a uuid.v1() applied to make mine unique to get around it but this is not working; https://github.com/solid/node-solid-server/blob/master/lib/ldp.js#L534
```
${uuid.v1().split('-')[0]}-${filename}`))
```
in the recursive ensureNotExists function

**Comment by kjetilk** [comment]
Right, so, we have `Slug` [in the spec](https://github.com/solid/solid-spec/blob/master/api-rest.md#creating-containers-directories), but it seems like the support for it is poor. We need to look into that.

**Comment by rimmartin** [comment]
A Slug: '.git' works fine Or any regular folder name.  It is only if the name is the same with a period prefixed .scad into scad/

**Comment by justinwb** [comment]
This would appear to be a pretty straightforward bug.

The Slug header comes from the ldp specification, which you can checkout here - https://www.w3.org/TR/ldp/

**Comment by gklyne** [comment]
FWIW, I too am having problems with "slug", but in my case I am not using a simple slug namer ("test1", etc.)

**Comment by csarven** [comment]
@gklyne Do you mean when trying to create an LDPC? I had issues with that recently, but didn't get a chance to inspect the source code. I've tried different combinations of HTTP methods, Link, Slug.. but no go. My expectation: https://github.com/solid/node-solid-server/issues/1107

**Comment by gklyne** [comment]
@csarven It was an error in my code.  It all works as expected.  Sorry for the noise.  (I deleted my comment hoping nobody had seen it yet :))

**Comment by gklyne** [comment]
@csarven, FWIW, I have been able to create an LDPC which seems to behave properly as a container.   (In case it helps, I'm working on a simple tool that can be used to probe a solid server, and also to support testing of an application that works with LDP containers. Work-in-progress at https://github.com/oerc-music/meld-cli-tools/tree/master/src/meld-tool.)

Sample commands using that (with node server running at https://localhost:8443/public/):

    source setenv.sh  # Set env for username, etc.
    node meld_tool.js ls /public/
    node meld_tool.js create-workset https://localhost:8443/public/ test1
    node meld_tool.js ls /public/
    node meld_tool.js create-workset https://localhost:8443/public/test1 test11
    node meld_tool.js ls /public/test1/

_etc._

**Comment by csarven** [comment]
@gklyne Thanks. That made me realise what I've overlooked: using LDPC and not LDP-BC (which is the only container type that's supported.) Updated #1107 for POST, and created https://github.com/solid/node-solid-server/issues/1108 for PUT.

**Comment by csarven** [comment]
Where scad/ does not exist.

```
$ curl -X POST -ikH'Content-Type: text/turtle' -H'Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel="type"' -H'Slug: .scad' https://csarven.localhost:8443/public/scad/

HTTP/1.1 404 Not Found
```

I believe that's correct since request target doesn't exist for `POST`.

As for:

```
$ curl -ikH'Content-Type: text/turtle' -H'Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel="type"' -H'Slug: .scad' https://csarven.localhost:8443/public/

201 Created

Location: /public/.scad/
```

Seems correct. Although use of `Slug` is discouraged or at the very least the server should not use client's slugtext "as is" - it should do its own naming, which was discussed in the past in this repository and in Solid Protocol, e.g., https://github.com/solid/specification/pull/621

Closing issue unless there is a particular behaviour that's desired which conflicts with expected (correct) behaviour.
